language: ruby
rvm:
- 2.0.0

before_script:
    - gem install kumogata

script:
    - bash validate.sh
    - which kumogata

after_success:
    - kumogata convert 001.rb

env:
  global:
    - secure: "vueUx2oITslXb0wHE5mssL1IKPAvjgtsLF2/zUJqFmfE3YGVMe9UcKYsJ8tB0xKOb2xEfcb5mKpEnb9mlMDEPN0HpIdAagrguJDPNI3IGonOQLvKVOD/heKJviCOOYogHV0iaXU5iGEIK9QMFkizkW1EjSJwU9Tt8Ew/MFswTE/7XAHUhVTyFMJ6vtfOgCFn3k8v8wJa22MiNyday0RaFWKzlISKRjFCJrP9JRDDihdAcMgXkFDmxoHx2rEBPKeisdTJYi4+NIMtzn6VJGwgLyk57xRiISmCHq2s+bMXyEKZqL8aDR4Wmjf6pX2atIc1IoZxRh4Fcss/zpIRuVAHd8oIpsBXl2w6EJUzq4ukAU4X8qcWYiP2OwjTZ+/InQBZ8921vh8z2sq2Ay5YOsJVoiE4xtGxY3GsuWQ/ObF55qPEHxlE2RU2BVThVENs1hrIcyKCPrxk9Fr69DF8+J1xMmj6DKdQtSNsL0XH24FQDwOpbXTa7DcfOmKC2odpLGJYUnJKNXVzWTOiAozh/V55HXwUtFScsJQwlDYSPQZQv2KBntkoSV0XyagaxOz10VHEnrAG0K/eFTrLXmURXvg9Jsoiz6GlTP3qFcHwNYBvRpDM1WIswgarzG6j72TCmatRol6jOr45822D5APjImMAcybLOThFlk0xRDpZ66XPgMI="
