language: ruby
rvm:
- 2.0.0

before_script:
    - gem install kumogata

script:
    - kumogata validate 001.rb
    - which kumogata
    - bash validate.sh

after_success:
    - kumogata convert 001.rb
