language: ruby
rvm:
- 2.0.0

before_script:
    - gem install kumogata

script:
    - which kumogata
    - bash ./bin/validate.sh

after_success:
    - bash ./bin/deploy.sh

env:
  global:
    - GIT_USER: Travis CI
    - GIT_EMAIL: hide.okamoto+github@digitalcube.jp
    - GH_REF: github.com/megumiteam/amimoto-enterprise-cfn.git
    - secure: "QYLI/AkFO+hgioig1xX593GT4KCAEeS4Lu1gMOXRCj6ydwAF6CL2KuPtHAmiTT3hvET5t95RCj1nELfO7ymQIHJVPDoRg8gefcaoC0IGfyV1UQBc2BVTP5dQ05mh8gMhuzn+pIW1gjM5m2tuFDlmgU8+2XZM8xfXsxcDpD75crouPy1mRaK6VGEIh6lC+m1wamIsFZJNma3Yagkso2WZQG8C7rRzSKipPYpOkfydbD+lv4OF2QagGbjg0foOO4VRGJETEULJmRFwk2ykP1w/DeBxoWxJksoTCQ/A1DXPhy3jqmIiHfXKlVHh119wQJG0Bb4md5Hc2fYf8lGPb5Zzy/FHqQsUyXDqcSbp9GGzKbh8DlIIqzgXfMNV186lujT5GjD1+7jeLmT+8VEnch7YhudAjEvxgVzu6iiGOSzL//jMZjAELFRilj8lc467PyiEySkpqf4QfuZJ1z49QBIEPlMJ7sdBlaOZsDN4AhI2fdPMR6wCZkJEuZigS4mrH2FC0avnGpcZzjQchv0cmOh9bZbL2kZPe97X318CtAelcog/2kNNat0ZhEQTvaz1y77U1l+8CbmS7MibPXEUBA0brUD6BaYUsYlW6G/7VxOxE21Ov+nQ96tcSEc/341TdmCOr/9spIRNlga75y01Aq4AJdUKFpF0HCYPSM7w20GCB4Q="
