language: ruby
rvm:
- 2.0.0

before_script:
    - gem install kumogata

script:
    - bash validate.sh
    - which kumogata

after_success:
    - kumogata convert 001.rb

env:
  global:
    - secure: "hojT9i2Mjpn6yfNg+lFIm/iBNGVp4Vq88s1JnBj9Vd5lQHnlV/Wj/TyN8T1WfWg8FsXXjhVKLDDiGpv/xuJ+bLSQwB2xKJyt1nMZM65DvIXbvlNWTg1V7Y9MloV/lgXdzKBr9CXodYyO4rg3usysa7/SSGpGYvG/G7kDBCQtAU1fOtyc3I4kZzPNbhbZYZlQTR9Q0O0Rl70ctlZFKxY5Nnt+JdrQAOGAOOq7n98owupO6LpwzObbuzjIpBeObLCzji5kIuK7zQhwsqHh8CPV4oU9M4CcnBZMtLyMwRFuxXF1OVrXqC3cAveQ2qD53DGF9XnGFYH0GTrcdHREEcTSeZMiYaR66vUFxAnvfNf9lIMqiVzjGcQ24JHEdb4pcydg7srPbGJXi0ivNJodBT4FMFVVmiYClYPBlfokHLRRrIneNbj6e7Dtq4B3/LY+D9ROc7KdjcUI3mvfC2KSj3RT0zf580KEjY5TubNcV9egM1dWAxIXG2IYXmi7M1UG1MonLBss6sAv0WZUVu+TSMti5aUWrvSRVlWNpfBTcUSY2N1jtZHAaaXILPbkYMZlaKaAt3o47gJ2IvlczYbygR5jT9xu80H/d+VwK6b7k8F6WSeCPy8sAkj3NeBJn8wWYJBp/nzPKYVbkg5usOnJnbGNmVbO2jDorriOrz+a8skuXcs="
