language: ruby
rvm:
- 2.0.0


script:
    - kumogata validate 001.rb
    - kumogata validate 001-mod.rb
    - kumogata validate 001-hhvm.rb
    - kumogata validate 001-hvm-aurora.rb
    - kumogata validate 001-woo-aurora.rb
    - kumogata validate 001-mod-aurora.rb
    - kumogata validate 001-hhvm-aurora.rb
    - kumogata validate 001-woo-hvm.rb
    - kumogata validate 001-woo-hhvm.rb
    - kumogata validate 001-woo-mod.rb

after_success:
    - kumogata convert 001.rb
